// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuLP2_-r0APuqWLxUh1pWt2EYd8TCop3g',
    appId: '1:513260275185:web:163ca65adb25a8d92cf050',
    messagingSenderId: '513260275185',
    projectId: 'twitter-clone-a0bfa',
    authDomain: 'twitter-clone-a0bfa.firebaseapp.com',
    storageBucket: 'twitter-clone-a0bfa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHmR1-hV3whjI1DKLipcYGVrwGP4ybiW4',
    appId: '1:513260275185:android:d45783b7bdd50cf02cf050',
    messagingSenderId: '513260275185',
    projectId: 'twitter-clone-a0bfa',
    storageBucket: 'twitter-clone-a0bfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClZylp27AQC5er5zGJFS0wsZ2KIEUQyPM',
    appId: '1:513260275185:ios:31c458b06fb2b4112cf050',
    messagingSenderId: '513260275185',
    projectId: 'twitter-clone-a0bfa',
    storageBucket: 'twitter-clone-a0bfa.appspot.com',
    iosClientId: '513260275185-4190k9rbtkgq3b2v9plsrc02cbqg6lp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClZylp27AQC5er5zGJFS0wsZ2KIEUQyPM',
    appId: '1:513260275185:ios:9bc4f89c53b163942cf050',
    messagingSenderId: '513260275185',
    projectId: 'twitter-clone-a0bfa',
    storageBucket: 'twitter-clone-a0bfa.appspot.com',
    iosClientId: '513260275185-4hn1s73ec4iu22d8qgicqkdgd3nd1brd.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterClone.RunnerTests',
  );
}
